apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: dev
  labels:
    app: api-gateway
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: mahesh541/api-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: dev
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  type: LoadBalancer  # Can also be NodePort or ClusterIP
