server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://service-registry.default.svc.cluster.local:8081/eureka

    fetch-registry: true
    register-with-eureka: true



spring:
  cloud:
    gateway:
      routes:
        - id: visitors-route
          uri: lb://visitor-service
          predicates:
            - Path=/visitors/**
          filters:
            - StripPrefix=0
        - id: appointments-route
          uri: lb://appointment-service
          predicates:
            - Path=/api/appointments/**
          filters:
            - StripPrefix=0
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=0
  application:
    name: api-gateway
springdoc:
  swagger-ui:
    urls:
      - name: "Visitor Service"
        url: http://visitor-service.default.svc.cluster.local:8080/v3/api-docs
      - name: "Appointment Service"
        url: http://appointment-service.default.svc.cluster.local:8080/v3/api-docs
      - name: "Notification Service"
        url: http://notification-service.default.svc.cluster.local:8080/v3/api-docs






