server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
spring:
  cloud:
    gateway:
      routes:
        - id: visitors-route
          uri: lb://visitor-management
          predicates:
            - Path=/visitors/**
          filters:
            - StripPrefix=0
  application:
    name: api-gateway