server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    prefer-ip-address: false
    hostname: localhost

spring:
  cloud:
    gateway:
      routes:
        - id: visitors-route
          uri: lb://visitor-service
          predicates:
            - Path=/visitors/**
          filters:
            - StripPrefix=0
        - id: appointments-route
          uri: lb://appointment-service
          predicates:
            - Path=/api/appointments/**
          filters:
            - StripPrefix=0
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=0
  application:
    name: api-gateway
springdoc:
  swagger-ui:
    urls:
      - name: "Visitor Service"
        url: http://localhost:2345/v3/api-docs
      - name: "Appointment Service"
        url: http://localhost:2346/v3/api-docs
      - name: "Notification Service"
        url: http://localhost:2347/v3/api-docs





